### ISSUE TITLE
Multiple binary versions

### ISSUE THREAD

**Issue by savitakartik** [ZhiGroup/RaPID#1]
Trying to use the RaPID binary provided on my cluster, I get the following:
./RaPID_v.1.0: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./RaPID_v.1.0)
./RaPID_v.1.0: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./RaPID_v.1.0)
It would be great if you could provide binary versions of RaPID against other distributions too, e.g. RHEL6/CentOS6.

Thanks!

**Comment by aabiddanda** [comment]
Just commenting here since it would be nice to have the source code available as well so that users could compile their own versions if possible to troubleshoot compilation issues themselves 

Thanks!

**Comment by ZhiGroup** [comment]
The source code is now released with RaPID V1.1
