### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by alex-medvedev-msc** [ZhiGroup/RaPID#11]
Hello,

I tried to run the example from readme.md and got segmentation fault (core dumped)

The exact command I used:
./RaPID_v.1.7 -i examples/4k_1e7.vcf.gz -g 4k_1e7_e0.001.g -d 5 -w 250 -r 10 -s 2 -o example_output

**Comment by ardalan-n** [comment]
Hi,

I think the genetic mapping file path was not provided properly. You can try the following command line:

./RaPID_v.1.7 -i examples/4k_1e7.vcf.gz -g **examples/4k_1e7_e0.001.g** -d 5 -w 250 -r 10 -s 2 -o example_output
