### ISSUE TITLE
munmap_chunk(): invalid pointer and segmentation fault

### ISSUE THREAD

**Issue by spoonogram** [ZhiGroup/RaPID#12]
rapid 1.7 worked fine for 4/6 of my chromosomes, but with chromosome 2 I get munmap_chunk and with chromosome 6 I get segmentation fault. All of my input files were created in one batch so there should be no formatting issues unique to these chromosomes. I tried on another computer and got the same errors. Any ideas?

**Comment by ardalan-n** [comment]
Hi, There are two common issues that could lead to segfault errors: Missing values or inconsistency between the provided genetic mapping file and the VCF file. Please make sure that the provided genetic mapping file contains values for all the sites in the VCF file.
Another (less common) issue might be related to hard disk space. The program writes some temporary files and if there's not enough space, it might crash. You can monitor the temporary files in the output folder.
