### ISSUE TITLE
clarification on how to make genetic map file?

### ISSUE THREAD

**Issue by brettva** [ZhiGroup/RaPID#14]
Hi,

I am trying to understand how to make the genetic map file.

For instance, I have `my_chr22_vcf.vcf` with 8,604 sites on chr22 (hg19 coordinates). 

Do I work from contents of `./genetic_maps`? such that:

```
python filter_mapping_file.py genetic_map_GRCh37_chr22.txt genetic_map_GRCh37_chr22_filtered.txt
python interpolate_loci.py genetic_map_GRCh37_chr22_filtered.txt my_chr22_vcf.vcf chr22.rMap
```
Thanks

**Comment by ardalan-n** [comment]
Hi,

Yes. `filter_mapping_file.py` outputs the longest monotonically increasing sites in the input genetic mapping file. It is used to make sure that the genetic distances/locations are (monotonically) increasing. The script `interpolate_loci.py` then takes the VCF file and the given genetic mapping file to interpolate the genetic distances/locations for all the sites in the VCF file.

Best,
Ardalan
