### ISSUE TITLE
interpolate_loci.py does not work on python3

### ISSUE THREAD

**Issue by biona001** [ZhiGroup/RaPID#16]
On python 3, I needed to change [line 16](https://github.com/ZhiGroup/RaPID/blob/master/interpolate_loci.py#L16) from 

`f = gzip.open(vcf_input)`

to

`f = gzip.open(vcf_input, 'rt')`

Seems like [gzip.open](https://docs.python.org/3/library/gzip.html) defaults to opening files in binary mode. The fix changes it to opening in text mode.

**Comment by ardalan-n** [comment]
Thank you very much for your comment! The script was written for Python 2.7 but I just revised the code so it can be run on Python 3 as well.
