### ISSUE TITLE
Immediate segmentation fault error (not related to memory max)

### ISSUE THREAD

**Issue by nswinford** [ZhiGroup/RaPID#17]
I cannot get RaPID to run and I'm at a loss as to why. My command is basically identical to your usage example:

/software/RaPID/RaPID_v.1.7 -i myFile.vcf.gz -g myMap.g -d 5 -o rapid_chr1/ -w 250 -r 10 -s 2

but when I run it I am immediately returned a segmentation fault error. I know segmentation faults can happen if memory gets maxed out, but this is not the issue. Is there a bug? I can't figure out why it won't run.

I also tried using the interpolate_loci.py script and was getting an int() error for float input, so I added a float() and the script ran, but it made the entire second column (genetic location) the same number (207.87). So I hope it's fine to use just the loci that are in the vcd without interpolation (but I don't think this would be related to the above error anyways).
Also, I assume that RaPID requires that the input be broken up by chromosome, like other IBD detection software. but I didn't see this mentioned in the usage. Is this the case?

Thank you!

**Comment by ardalan-n** [comment]
Hi,

I think there is an issue with the genetic map file even if there was no segfault error. The first column is simply the site index and the second column is the genetic location for each variant site in the VCF file. The number of variant sites in the genetic map file should also match the number of variant sites in the VCF file. I'd recommend using the interpolate_loci.py as you did. 

_when I run it I am immediately returned a segmentation fault error. I know segmentation faults can happen if memory gets maxed out, but this is not the issue. Is there a bug? I can't figure out why it won't run._
Please make sure that the physical locations in your VCF file are integers. The fact that you get an int() error for float input implies that the physical locations are probably not stored as integers. Please double-check your VCF file and make sure the second column in the VCF file contains the physical locations.

_Also, I assume that RaPID requires that the input be broken p by chromosome, like other IBD detection software. but I didn't see this mentioned in the usage. Is this the case?_
Yes. Each chromosome should be provided in a separate file.


Best,
Ardalan

**Comment by nswinford** [comment]
Thank you. Yes, it was an issue with the genetic map file and once I fixed it, it ran.
