### ISSUE TITLE
MaCS format issue

### ISSUE THREAD

**Issue by jnaitsaada** [ZhiGroup/RaPID#3]
Hi,

I tried to use your script to convert VCF files to MaCS format. It worked but when I try to run RaPID on this new file, I get an error :

./RaPID_v.1.2 -i essaiMACS2 s -o data/10Mbp2000indRaPID -r 10 -w 35 -s 2 -l 1.5 -t 10
Create sub-samples..
Done!
Minimum length in terms of SNPs: 323
FATAL ERROR: end of line error for MaCS SITE 24

If I remove the line corresponding to the site 24, I just get an error related to another site, and so on... RaPID works perfectly fine with the example data of a panel with 4000 haplotypes with the chromosome length of 10Mbps in macs format you provided.

Do you have any idea of what could be the problem ?

I added to the script some code to add the last missing lines of MaCS format :
TOTAL_SAMPLES: 
TOTAL_SITES: 
BEGIN_SELECTED_SITES
END_SELECTED_SITES

But I still have the same error.

Maybe it is related to the first line :
COMMAND: ./macs 2000 10 -t 0.001 -r 0.001

In the example data provided, this line is much more complex.

**Comment by ardalan-n** [comment]
Hi,

This error occurs if the number of alleles in a site is less than expected. How many individuals (haplotypes) are in your panel? Does your data set contain missing values? By the way, after ./macs in the first line, the number of haplotypes should be mentioned.

**Comment by jnaitsaada** [comment]
Hi

You were right indeed. There was a mistake in the first line, the number of haplotypes was wrong (I had 1000 haplotypes and not 2000). Now it works perfectly fine!

Thank you!
