### ISSUE TITLE
License Expired

### ISSUE THREAD

**Issue by XLZH** [ZhiGroup/RaPID#5]
Dr. Zhi,

when I run the RaPID_v.1.6, it said that "The license has expired! Please contact the authors."
So, what should I do to run the program? thanks!

**Comment by psnavais** [comment]
The same problem for me. It only happens with v.1.6.
Thanks

**Comment by ardalan-n** [comment]
Please use the version v.1.2 for now. We're still working on v.1.6.

You can also use this script to convert VCF into MaCS format (input file format for v.1.2):
http://genome.ucf.edu/RaPID/convert_vcf_to_macs.py

**Comment by zhizhid** [comment]
Now you can use v1.7.  All previous versions are obsolete.
