### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by msesia** [ZhiGroup/RaPID#8]
I downloaded this repository and tried to reproduce the example in the README, but I obtained this error message.

```
$ ./RaPID_v.1.7 -i 4k_1e7.vcf.gz -g 4k_1e7_e0.001.g -d 5 -w 250 -r 10 -s 2 -o output_folder
Create sub-samples..
Done!
FATAL ERROR: failed to get M
```
EDIT: I think the problem is that the path to the input files should include "examples/".

**Comment by ardalan-n** [comment]
The absolute or relative path to the input file should be provided as an argument with -i. 

Best,
Ardalan
