### ISSUE TITLE
script parameter_estimation

### ISSUE THREAD

**Issue by RobinHofmeister** [ZhiGroup/RaPID#9]
thank for sharing the RaPID software which is working well.

However, I am trying to find optimal parameters using the script provided and I have several issues.

When the input vcf file is phased, I had to modify the line 37 to change "/" to "|" (minor change, not important..).

When I then run the script using the example file, I got no results. The script is running without any errors but no output file is written and there is no std output on the shell.

I found that in the for loop of the function "compute_w" , there is " if " and " elif " but no "else" and the 300 iterations are going into the "else" option.

**Comment by ardalan-n** [comment]
Thank you for your comment. I just made minor changes to the script and it should work now for phased data as well. It should also output the range even if the max window is still within the permissible range.

Best,
Ardalan
